### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by cswwp** [ovysotska/image_sequence_localizer#34]
@ovysotska  Hi, thanks for sharing so great work. But i can't find time-continious dataset to run the demo. Do you mind to supply the dataset. Thanks again.

**Comment by ovysotska** [comment]
Hey @cswwp ,
in theory, any two sequences of images that show the same place in the environment should work.
Nevertheless, you could try one of the public datasets:
* Native to this code: https://www.ipb.uni-bonn.de/data/visual-place-recognition-datasets/index.html
* Nordland: https://nrkbeta.no/2013/01/15/nordlandsbanen-minute-by-minute-season-by-season/
